USE master
GO
IF DB_ID('PTTK') IS NOT NULL
	DROP DATABASE PTTK
GO --KẾT THÚC KHỐI LỆNH Ở TRÊN
CREATE DATABASE QLDT_1
GO
USE PTTK 


CREATE CHINHANH 
(
    MACN NVARCHAR(5),
    TENCN NVARCHAR(50),
    DIACHI NVARCHAR(100),
    SDT NVARCHAR(13)

    CONSTRAINT PK_CN
    PRIMARY KEY(MACN)
)

CREATE TABLE QUIDINH
(
    MAQD CHAR(5),
    PHANLOAI VARCHAR(5),
    TENCD NVARCHAR(50),
    MACN NVARCHAR(5)

    CONSTRAINT PK_CD
    PRIMARY KEY(MACD),
    CONSTRAINT FK_CD_CN
    FOREIGN KEY(MACN)
)

CREATE TABLE NHANVIEN
(
    MANV CHAR(5),
    HOTEN NVARCHAR(50),
    PHAI NVARCHAR(5),
    NGAYSINH DATE,
    DIACHI NVARCHAR(100),
    MACN NVARCHAR(5),
    VAITRO VARCHAR(5),

    CONSTRAINT PK_NV
    PRIMARY KEY(MANV),
    CONSTRAINT CK_NV_PHAI
    CHECK (PHAI = 'NAM' OR PHAI = N'NỮ'),
    CONSTRAINT FK_NV_CN
    FOREIGN KEY(MACN)
)

CREATE TABLE HOADON
(
    MAHD CHAR(5),
    TONGTIEN FLOAT,
    HINHTHUCTT CHAR(2),
    NGAYLAP DATE,
    MANV CHAR(5),
    
    CONSTRAINT PK_HD
    PRIMARY KEY(MAHD),
    CONSTRAINT FK_HD_NV
)

-- INSERT VALUES
-- CHI NHANH
INSERT INTO VALUES ('CN1', 'Chi nhánh 1', '123 Đường 1', '0123456789')
-- QUI DINH
INSERT INTO VALUES ('QD1', 'TT001', 'TT', 'CN1')
-- NHAN VIEN
INSERT INTO VALUES ('NV1', 'Nguyễn Văn A', 'NAM', '1999-01-01', '123 Đường 1', 'CN1', 'NV')
